{
    "name": "Nursing Home Vistation",
    "summary": """Vistation management""",
    "category": "Uncategorized",
    "version": "13.0.0.1",
    "author": "Waite Perpectives, LLC - Zach Waite",
    "depends": [
        "website",
        "base_automation",
    ],
    "data": [
        "security/groups.xml",
        "security/ir.model.access.csv",
        "data/defaults.xml",
        "data/rpc_user.xml",
        "data/automated_actions.xml",
        "data/mail_templates.xml",
        "security/rules.xml",
        "views/assets.xml",
        "views/views.xml",
        "views/actions.xml",
        "views/menus.xml",
        "views/templates.xml",
        "reports/screening_report.xml",
    ],
    "demo": ["demo/data.xml"],
    "qweb": ["static/src/xml/*"],
    "images": [],
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "application": False,
    "auto_install": False,
    "installable": True,
    # 'external_dependencies': {'python': [], 'bin': []},
    # 'support': 'zach@waiteperspectives.com',
    # 'website': 'www.waiteperspectives.com',
    # 'license': 'LGPL-3',
    # 'price': 999.00,
    # 'currency': 'USD',
}
