.PHONY: singlefile

singlefile: visitationAppIO.js visitationAppBase.js visitationAppStepper.js visitationAppResidentForm.js visitationAppVisitorForm.js visitationAppSchedulingForm.js visitationAppResultsForm.js visitationAppMain.js visitationApp.js
	cat visitationAppIO.js > visitationAppAll.js
	cat visitationAppBase.js >> visitationAppAll.js
	cat visitationAppStepper.js >> visitationAppAll.js
	cat visitationAppResidentForm.js >> visitationAppAll.js
	cat visitationAppVisitorForm.js >> visitationAppAll.js
	cat visitationAppSchedulingForm.js >> visitationAppAll.js
	cat visitationAppResultsForm.js >> visitationAppAll.js
	cat visitationAppMain.js >> visitationAppAll.js
	cat visitationApp.js >> visitationAppAll.js 


